---
version: 3.14.0
hassio_api: true
slug: foxden_nginx_proxy
name: FoxDen nginx + acme.js
description: FoxDen nginx + acme.js
url: https://github.com/FoxDenHome/ha-addons-fork/tree/master/nginx_proxy
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - ssl:rw
  - share
options:
  domain: null
  email: null
  hsts: max-age=31536000; includeSubDomains
  cloudflare: false
  customize:
    active: false
    default: nginx_proxy_default*.conf
    servers: nginx_proxy/*.conf
  real_ip_from: []
ports:
  443/tcp: 443
  444/tcp: 444
  80/tcp: 80
  81/tcp: 81
schema:
  domain: str
  email: str
  hsts: str
  cloudflare: bool
  customize:
    active: bool
    default: str
    servers: str
  real_ip_from:
    - str
